---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-v2
  namespace: api
  labels:
    app: api
    version: v2
    service: fake-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      namespace: api
      labels:
        app: api
        service: fake-service
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/transparent-proxy: 'true'
        #consul.hashicorp.com/envoy-extra-args: '--log-level debug --disable-hot-restart'
        consul.hashicorp.com/service-tags: 'v2'
        consul.hashicorp.com/service-meta-version: 'v2'
    spec:
      serviceAccountName: api
      containers:
        - name: api
          image: nicholasjackson/fake-service:v0.26.0
          ports:
            - containerPort: 9091
          env:
            - name: 'LISTEN_ADDR'
              value: '127.0.0.1:9091'
            - name: 'NAME'
              value: 'api-v2 (default.ap/api.ns)'
            - name: 'MESSAGE'
              value: 'API response'
            - name: 'SERVER_TYPE'
              value: 'http'
            - name: 'ERROR_TYPE'
              value: 'delay'
            - name: 'TIMING_50_PERCENTILE'
              value: '1000ms'
            - name: 'TIMING_90_PERCENTILE'
              value: '1400ms'
            - name: 'TIMING_99_PERCENTILE'
              value: '1500ms'
            - name: 'HTTP_SERVER_READ_TIMEOUT'
              value: '0s'
            - name: 'HTTP_SERVER_WRITE_TIMEOUT'
              value: '0s'
            - name: 'HTTP_CLIENT_APPEND_REQUEST'
              value: 'true'