apiVersion: consul.hashicorp.com/v1alpha1
kind: ExportedServices
metadata:
  name: default ## The name of the partition containing the service
spec:
  services:
    - name: mesh-gateway
      namespace: default
      consumers:
        - samenessGroup: shared-sameness-group
    - name: web ## The name of the service you want to export
      namespace: web
      consumers:
        - samenessGroup: shared-sameness-group
    - name: api ## The name of the service you want to export
      namespace: api
      consumers:
        - samenessGroup: shared-sameness-group
    - name: payments ## The name of the service you want to export
      namespace: payments
      consumers:
        - samenessGroup: shared-sameness-group