---
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: api-migration
spec:
  destination:
    name: api
    namespace: api
  sources:
    - name: api-gateway
      namespace: default
      partition: default
      action: allow
    - name: web
      namespace: web
      action: allow
    - name: web
      namespace: default
      partition: default
      action: allow