apiVersion: v1
kind: ServiceAccount
metadata:
  name: api
  namespace: api
---
apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: api
spec:
  selector:
    app: api
  ports:
    - port: 9091
      targetPort: 9091
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-v2
  namespace: api
  labels:
    app: api
    version: v2
    service: fake-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      namespace: api
      labels:
        app: api
        service: fake-service
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/transparent-proxy: 'true'
        #consul.hashicorp.com/envoy-extra-args: '--log-level debug --disable-hot-restart'
        consul.hashicorp.com/service-tags: 'v2'
        consul.hashicorp.com/service-meta-version: 'v2'
    spec:
      serviceAccountName: api
      containers:
        - name: api
          image: nicholasjackson/fake-service:v0.26.0
          ports:
            - containerPort: 9091
          env:
            - name: 'LISTEN_ADDR'
              value: '127.0.0.1:9091'
            #- name: 'UPSTREAM_URIS'
            #  value: 'grpc://currency.currency-ns:9090,http://payments.payments-ns:9090'
            - name: 'NAME'
              value: 'api-v2 (default.ap/api.ns)'
            - name: 'MESSAGE'
              value: 'API response'
            - name: 'SERVER_TYPE'
              value: 'http'
            - name: 'ERROR_TYPE'
              value: 'http_error'
            - name: 'ERROR_RATE'
              value: "0.50"
            - name: "ERROR_DELAY"
              value: '1s'
            - name: 'TIMING_50_PERCENTILE'
              value: '20ms'
            - name: 'TIMING_90_PERCENTILE'
              value: '30ms'
            - name: 'TIMING_99_PERCENTILE'
              value: '40ms'
            - name: 'TIMING_VARIANCE'
              value: '10'
            - name: 'HTTP_SERVER_READ_TIMEOUT'
              value: '0s'
            - name: 'HTTP_SERVER_WRITE_TIMEOUT'
              value: '0s'
            - name: 'HTTP_CLIENT_APPEND_REQUEST'
              value: 'true'
