apiVersion: consul.hashicorp.com/v1alpha1
kind: ExportedServices
metadata:
  name: shared ## The name of the partition containing the service
spec:
  services:
    - name: mesh-gateway
      namespace: default
      consumers:
        - partition: default
    - name: web ## The name of the service you want to export
      namespace: web
      consumers:
        - partition: default
    - name: api ## The name of the service you want to export
      namespace: api
      consumers:
        - partition: default