apiVersion: consul.hashicorp.com/v1alpha1
kind: PeeringDialer
metadata:
  name: usw2-default ## The name of the peer you want to connect to
  namespace: consul
spec:
  peer:
    secret:
      name: "peering-token-use1-default"
      key: "data"
      backend: "kubernetes"
