apiVersion: v1
kind: ServiceAccount
metadata:
  name: consulcli
  namespace: consul
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consulcli
  namespace: consul
  labels:
    app: consulcli
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consulcli
  template:
    metadata:
      namespace: consul
      labels:
        app: consulcli
      annotations:
        consulcli.hashicorp.com/connect-inject: 'false'
    spec:
      serviceAccountName: consulcli
      containers:
        - name: consulcli
          image: hashicorp/consul:1.15
          # securityContext:
          #   capabilities:
          #     add: ["NET_ADMIN", "SYS_TIME"]
