apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: payments
spec:
  destination:
    name: payments
    namespace: payments
  sources:
    - name: api
      namespace: api
      action: allow
      samenessGroup: shared-sameness-group