apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments
  namespace: payments
---
apiVersion: v1
kind: Service
metadata:
  name: payments
  namespace: payments
spec:
  selector:
    app: payments
  ports:
    - port: 9091
      targetPort: 9091
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-v1
  namespace: payments
  labels:
    app: payments
    version: v1
    service: fake-service
spec:
  replicas: 3
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      namespace: payments
      labels:
        app: payments
        service: fake-service
      annotations:
        consul.hashicorp.com/connect-inject: 'true'
        consul.hashicorp.com/transparent-proxy: 'true'
        consul.hashicorp.com/service-tags: 'v1'
        consul.hashicorp.com/service-meta-version: 'v1'
    spec:
      serviceAccountName: payments
      containers:
        - name: payments
          image: nicholasjackson/fake-service:v0.26.0
          ports:
            - containerPort: 9091
          env:
            - name: 'LISTEN_ADDR'
              value: '127.0.0.1:9091'
            - name: 'NAME'
              value: 'payments-v1 (default.ap/payments.ns)'
            - name: 'MESSAGE'
              value: 'payments response'
            - name: 'SERVER_TYPE'
              value: 'http'
            - name: 'ERROR_TYPE'
              value: 'delay'
            - name: 'ERROR_RATE'
              value: "0.5"
            - name: "ERROR_DELAY"
              value: '4s'
            - name: "ERROR_CODE"
              value: '500'
            - name: 'TIMING_50_PERCENTILE'
              value: '15000ms'
            - name: 'TIMING_90_PERCENTILE'
              value: '15000ms'
            - name: 'TIMING_99_PERCENTILE'
              value: '15000ms'
            - name: 'HTTP_SERVER_READ_TIMEOUT'
              value: '0s'
            - name: 'HTTP_SERVER_WRITE_TIMEOUT'
              value: '0s'
            - name: 'HTTP_CLIENT_APPEND_REQUEST'
              value: 'true'